# 推送系统配置

spring:
  data:
    # Mongodb数据库
    mongodb:
      database: im-center
      uri: mongodb://39.106.100.78:27010/im-center
  # Redis数据库
  redis:
    host: 39.106.100.78
    port: 6300
    password: HANchu123
    database: 3
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 0

  # 监控
  zipkin:
    base-url: https://www.kdmilk.com:9411

# logging日志
logging:
  file: logs/dev_im.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.lili.imcenter: ERROR
logstatus: false
