# 统计系统配置

spring:
  # MySql数据库
  datasource:
      url: jdbc:mysql://47.104.194.42:3306/users?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: HANchu123
      driverClassName: com.mysql.jdbc.Driver
  data:
    # es搜索
    elasticsearch:
          cluster-name: "lili-es"
          cluster-nodes: 47.104.184.121:9300
    # Mongodb数据库


  # Redis数据库
  redis:
      host: 47.104.184.121
      port: 6300
      password: HANchu123
      database: 7
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 10
        min-idle: 0
      timeout: 0

  # 监控
  zipkin:
    base-url: http://47.104.194.42:9411

# logging日志
logging:
  file: logs/dev_statis.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: INFO
    com.lili.statiscenter: INFO
mongodb:
  ordercenter:
    host: 47.104.184.121
    port: 27010
    database: order-center

  usercenter:
    host: 47.104.184.121
    port: 27010
    database: user-center

  activecenter:
    host: 47.104.184.121
    port: 27010
    database: active-center
  paycenter:
    host: 47.104.184.121
    port: 27010
    database: pay-center

logstatus: false
